# use [colorChar] to color(DON'T ASK ME THE COLOR CODE XD)
# THE DEEP DARK FANTASIES.

info:
  register: "==========================================================================\n
              \n&b欢迎您第一次来到本服务器！请输入/register 密码 密码 以便注册账号~\n
             \n&r=========================================================================="
  login: "==========================================================================\n
            \n&b欢迎回来！请输入/login 密码 以便登入服务器~\n
          \n&r=========================================================================="

succ:
  register: "&a注册成功！欢迎━(*｀∀´*)ノ亻!"
  login: "&a登入成功！欢迎回来~"

error:
  login: "&e密码错误，再输入一次嘛~"
  notAllowSpeak: "&c你还登入或注册呢~ 说啥话呢~ &b=w="
  notAllowUseCommand: "&c你还登入或注册呢~ 输啥命令呢~ &b=w="
  hasLogin: "&c您已经登入过啦~"
  hasRegister: "&c您已经注册过啦~ 输入&e&l/login 密码 &c以便登入~"
  notRegister: "&c您还没注册呢~ 输入 &e&l/register 密码 密码 &c以便注册~"
  passwordNotSame: "&c您两次输入的密码不一致哟~ 请再输入一次!&b;w;"
  outOfRange: "&c&l参数错误，请重新检查!"
  pwdPattenWrong: "&c密码不合法哟，至少6-16个字符，至少1个大写字母，1个小写字母和1个数字"

other:
  # 密码正则表达式 如果不要求则填空着
  # 至少6-16个字符，至少1个大写字母，1个小写字母和1个数字
  # 请务必使用转义符\\
  # https://www.cnblogs.com/daizhongxing/p/11593137.html
  pwdPatten: "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{6,16}$"